services:
  nginx-rtmp:
    image: tiangolo/nginx-rtmp
    container_name: nginx-rtmp
    ports:
      - 1935:1935
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./streams:/tmp/streams  # HLS/DASH сегменты
      - ./html:/var/www/html         # Для HTML-плеера
    networks:
      - rtmp-network
    restart: unless-stopped

networks:
  rtmp-network:
    external: true